vim.g.mapleader = " "
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.timeoutlen = 250
vim.opt.wrap = false
vim.opt.hlsearch = false
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "80"
